routes/web.php
<?php

//RUN THIS IN PRODUCTION TO CREATE A STORAGE LINK  www.example.com/linkstorage
Route::get('/linkstorage', function () {
    Artisan::call('storage:link');
});


Route::get('/home', function () {
    if (session('status')) {
        return redirect()->route('admin.shops.index')->with('status', session('status'));
    }

    return redirect()->route('admin.shops.index');
});
Route::get('/', function () {
    return view('auth.login');
});
//Route::get('/', 'HomeController@index')->name('home');
Route::get('shop/{shop}', 'HomeController@show')->name('shop');

Auth::routes();

Route::group(['prefix' => 'admin', 'as' => 'admin.', 'namespace' => 'Admin', 'middleware' => ['auth']], function () {
    Route::get('/', 'HomeController@index')->name('home');
    // Permissions
    Route::delete('permissions/destroy', 'PermissionsController@massDestroy')->name('permissions.massDestroy');
    Route::resource('permissions', 'PermissionsController');

    // Roles
    Route::delete('roles/destroy', 'RolesController@massDestroy')->name('roles.massDestroy');
    Route::resource('roles', 'RolesController');

    // Users
    Route::delete('users/destroy', 'UsersController@massDestroy')->name('users.massDestroy');
    Route::resource('users', 'UsersController');

    // Categories
    Route::delete('categories/destroy', 'CategoriesController@massDestroy')->name('categories.massDestroy');
    Route::resource('categories', 'CategoriesController');

    // Shops
    Route::delete('shops/destroy', 'ShopsController@massDestroy')->name('shops.massDestroy');
    Route::post('shops/media', 'ShopsController@storeMedia')->name('shops.storeMedia');
    Route::resource('shops', 'ShopsController');


});


Route::get('page', ['as' => 'page.index',  'uses' => 'DashboardController@index']);

// ADMIN CATEGORY

Route::group(['middleware'=>'permissions:categories'],function (){
   Route::get('/category','Admin\CategoryController@index')->name('admin-cat-index');
});

//SUBCATEGORIES
Route::get('/sub-index', 'Admin\SubCategoriesController@subIndex')->name('sub-index');
Route::get('/sub-create', 'Admin\SubCategoriesController@subCreate')->name('sub-create');
Route::get('show-sub/{category}', 'Admin\SubCategoriesController@subShow')->name('sub-show');
Route::get('edit-sub/{category}', 'Admin\SubCategoriesController@subEdit')->name('sub-edit');
Route::delete('delete-sub/{category}', 'Admin\SubCategoriesController@subDestroy')->name('sub-delete');
Route::post('sub-store', 'Admin\SubCategoriesController@subStore')->name('sub-store');
Route::post('update-sub/{category}', 'Admin\SubCategoriesController@subUpdate')->name('sub-update');
Route::delete('categories/destroy', 'Admin\SubCategoriesController@massDestroy')->name('sub-massDestroy');

Route::post('/subcategory/edit/{id}', 'Admin\SubCategoriesController@update')->name('admin-subcat-update');

//CHILD CATEGORIES
Route::get('/child-index', 'Admin\ChildCategoryController@index')->name('child-index');
Route::get('/child-create', 'Admin\ChildCategoryController@create')->name('child-create');
Route::get('show/{category}', 'Admin\ChildCategoryController@show')->name('child-show');
Route::get('edit/{category}', 'Admin\ChildCategoryController@edit')->name('child-edit');
Route::delete('delete/{category}', 'Admin\ChildCategoryController@destroy')->name('child-delete');
Route::post('store', 'Admin\ChildCategoryController@store')->name('child-store');
Route::post('update/{category}', 'Admin\ChildCategoryController@update')->name('child-update');

Route::get('/bacon-index', 'Admin\BaconController@index')->name('bacon-index');
Route::get('/bacon-create', 'Admin\BaconController@create')->name('bacon-create');
Route::get('show-bacon/{bacon}', 'Admin\BaconController@show')->name('bacon-show');
Route::get('edit-bacon/{bacon}', 'Admin\BaconController@edit')->name('bacon-edit');
Route::delete('delete-bacon/{bacon}', 'Admin\BaconController@destroy')->name('bacon-delete');
Route::post('bacon-store', 'Admin\BaconController@store')->name('bacon-store');
Route::post('update-bac/{bacon}', 'Admin\BaconController@update')->name('bacon-update');

Route::get('/extra-index', 'Admin\BreakfastExtraController@index')->name('extra-index');
Route::get('/extra-create', 'Admin\BreakfastExtraController@create')->name('extra-create');
Route::get('show-extra/{extra}', 'Admin\BreakfastExtraController@show')->name('extra-show');
Route::get('edit-extra/{extra}', 'Admin\BreakfastExtraController@edit')->name('extra-edit');
Route::delete('delete-extra/{extra}', 'Admin\BreakfastExtraController@destroy')->name('extra-delete');
Route::post('extra-store', 'Admin\BreakfastExtraController@store')->name('extra-store');
Route::post('update-extra/{extra}', 'Admin\BreakfastExtraController@update')->name('extra-update');


Route::get('/eggs-index', 'Admin\EggsController@index')->name('eggs-index');
Route::get('/eggs-create', 'Admin\EggsController@create')->name('eggs-create');
Route::get('show-eggs/{eggs}', 'Admin\EggsController@show')->name('eggs-show');
Route::get('edit-eggs/{eggs}', 'Admin\EggsController@edit')->name('eggs-edit');
Route::delete('delete-eggs/{eggs}', 'Admin\EggsController@destroy')->name('eggs-delete');
Route::post('eggs-store', 'Admin\EggsController@store')->name('eggs-store');
Route::post('update-eggs/{eggs}', 'Admin\EggsController@update')->name('eggs-update');

Route::get('/coffee-index', 'Admin\CoffeeController@index')->name('coffee-index');
Route::get('/coffee-create', 'Admin\CoffeeController@create')->name('coffee-create');
Route::get('show-coffee/{coffee}', 'Admin\CoffeeController@show')->name('coffee-show');
Route::get('edit-coffee/{coffee}', 'Admin\CoffeeController@edit')->name('coffee-edit');
Route::delete('delete-coffee/{coffee}', 'Admin\CoffeeController@destroy')->name('coffee-delete');
Route::post('coffee-store', 'Admin\CoffeeController@store')->name('coffee-store');
Route::post('update-coffee/{coffee}', 'Admin\CoffeeController@update')->name('coffee-update');

resources/views/admin/extra/create.blade.php
@extends('layouts.admin')



@section('content')
    <div class="content">
        <div class="card">
            <div class="card-header">
                {{ trans('global.create') }} {{ 'Breakfast Extra List' }}
            </div>

            <div class="card-body">
                <form method="POST" action="{{ route("extra-store") }}" enctype="multipart/form-data">
                    @csrf
                    <div class="form-group">
                        <label class="required" for="name">{{ trans('cruds.shop.fields.name') }}</label>
                        <input class="form-control {{ $errors->has('name') ? 'is-invalid' : '' }}" type="text"
                               name="name" id="name" value="{{ old('name', '') }}" required>
                        @if($errors->has('name'))
                            <div class="invalid-feedback">
                                {{ $errors->first('name') }}
                            </div>
                        @endif
                        <span class="help-block">{{ trans('cruds.shop.fields.name_helper') }}</span>
                    </div>

                    <div class="form-group">
                        <label for="description">{{ 'Description(Optional)' }}</label>
                        <textarea class="form-control {{ $errors->has('description') ? 'is-invalid' : '' }}"
                                  name="description" id="description">{{ old('description') }}</textarea>
                        @if($errors->has('description'))
                            <div class="invalid-feedback">
                                {{ $errors->first('description') }}
                            </div>
                        @endif
                        <span class="help-block">{{ trans('cruds.shop.fields.description_helper') }}</span>
                    </div>
                    <div class="form-group">
                        <label for="price">{{ 'Price(Optional)' }}</label>
                        <input class="form-control {{ $errors->has('price') ? 'is-invalid' : '' }}" type="text"
                               name="price" id="price" value="{{ old('price', '') }}">
                        @if($errors->has('price'))
                            <div class="invalid-feedback">
                                {{ $errors->first('price') }}
                            </div>
                        @endif
                        <span class="help-block">{{ trans('cruds.shop.fields.name_helper') }}</span>
                    </div>
                    <div class="form-group">
                        <label for="photos">{{ 'Photos(Optional)' }}</label>
                        <div class="needsclick dropzone {{ $errors->has('photos') ? 'is-invalid' : '' }}"
                             id="photos-dropzone">
                        </div>
                        @if($errors->has('photos'))
                            <div class="invalid-feedback">
                                {{ $errors->first('photos') }}
                            </div>
                        @endif
                        <span class="help-block">{{ trans('cruds.shop.fields.photos_helper') }}</span>
                    </div>


                    <div class="form-group">
                        <button class="btn btn-danger" type="submit">
                            {{ trans('global.save') }}
                        </button>
                    </div>
                </form>



            </div>
        </div>
    </div>
@endsection

@section('scripts')
    <script
        src="https://maps.googleapis.com/maps/api/js?key={{ env('GOOGLE_MAPS_API_KEY') }}&libraries=places&callback=initialize&language=en&region=GB"
        async defer></script>
    <script src="/js/mapInput.js"></script>
{{--    <script>--}}
{{--        var uploadedPhotosMap = {}--}}
{{--        Dropzone.options.photosDropzone = {--}}
{{--            url: '{{ route('admin.bacon.storeMedia') }}',--}}
{{--            maxFilesize: 2, // MB--}}
{{--            acceptedFiles: '.jpeg,.jpg,.png,.gif',--}}
{{--            addRemoveLinks: true,--}}
{{--            headers: {--}}
{{--                'X-CSRF-TOKEN': "{{ csrf_token() }}"--}}
{{--            },--}}
{{--            params: {--}}
{{--                size: 2,--}}
{{--                width: 4096,--}}
{{--                height: 4096--}}
{{--            },--}}
{{--            success: function (file, response) {--}}
{{--                $('form').append('<input type="hidden" name="photos[]" value="' + response.name + '">')--}}
{{--                uploadedPhotosMap[file.name] = response.name--}}
{{--            },--}}
{{--            removedfile: function (file) {--}}
{{--                console.log(file)--}}
{{--                file.previewElement.remove()--}}
{{--                var name = ''--}}
{{--                if (typeof file.file_name !== 'undefined') {--}}
{{--                    name = file.file_name--}}
{{--                } else {--}}
{{--                    name = uploadedPhotosMap[file.name]--}}
{{--                }--}}
{{--                $('form').find('input[name="photos[]"][value="' + name + '"]').remove()--}}
{{--            },--}}
{{--            init: function () {--}}
{{--                @if(isset($bacon) && $bacon->photos)--}}
{{--                var files =--}}
{{--                {!! json_encode($bacon->photos) !!}--}}
{{--                    for (var i in files) {--}}
{{--                    var file = files[i]--}}
{{--                    this.options.addedfile.call(this, file)--}}
{{--                    this.options.thumbnail.call(this, file, file.url)--}}
{{--                    file.previewElement.classList.add('dz-complete')--}}
{{--                    $('form').append('<input type="hidden" name="photos[]" value="' + file.file_name + '">')--}}
{{--                }--}}
{{--                @endif--}}
{{--            },--}}
{{--            error: function (file, response) {--}}
{{--                if ($.type(response) === 'string') {--}}
{{--                    var message = response //dropzone sends it's own error messages in string--}}
{{--                } else {--}}
{{--                    var message = response.errors.file--}}
{{--                }--}}
{{--                file.previewElement.classList.add('dz-error')--}}
{{--                _ref = file.previewElement.querySelectorAll('[data-dz-errormessage]')--}}
{{--                _results = []--}}
{{--                for (_i = 0, _len = _ref.length; _i < _len; _i++) {--}}
{{--                    node = _ref[_i]--}}
{{--                    _results.push(node.textContent = message)--}}
{{--                }--}}
{{--                return _results--}}
{{--            }--}}
{{--        }--}}
{{--    </script>--}}
@endsection

resources/views/admin/extra/edit.blade.php
@extends('layouts.admin')
@section('content')
    <div class="content">

<div class="card">
    <div class="card-header">
        {{ trans('global.edit') }} {{ 'Breakfast Extra' }}
    </div>

    <div class="card-body">
        <form method="POST" action="{{ route("extra-update", [$extra->id]) }}" enctype="multipart/form-data">
            @csrf
            <div class="form-group">
                <label class="required" for="name">{{ trans('cruds.shop.fields.name') }}</label>
                <input class="form-control {{ $errors->has('name') ? 'is-invalid' : '' }}" type="text" name="name" id="name" value="{{ old('name', $extra->name) }}" required>
                @if($errors->has('name'))
                    <div class="invalid-feedback">
                        {{ $errors->first('name') }}
                    </div>
                @endif
                <span class="help-block">{{ trans('cruds.shop.fields.name_helper') }}</span>
            </div>

            <div class="form-group">
                <label for="description">{{ trans('cruds.shop.fields.description') }}</label>
                <textarea class="form-control {{ $errors->has('description') ? 'is-invalid' : '' }}" name="description" id="description">{{ old('description', $extra->description) }}</textarea>
                @if($errors->has('description'))
                    <div class="invalid-feedback">
                        {{ $errors->first('description') }}
                    </div>
                @endif
                <span class="help-block">{{ trans('cruds.shop.fields.description_helper') }}</span>
            </div>
            <div class="form-group">
                <label for="photos">{{ trans('cruds.shop.fields.photos') }}</label>
                <div class="needsclick dropzone {{ $errors->has('photos') ? 'is-invalid' : '' }}" id="photos-dropzone">
                </div>
                @if($errors->has('photos'))
                    <div class="invalid-feedback">
                        {{ $errors->first('photos') }}
                    </div>
                @endif
                <span class="help-block">{{ trans('cruds.shop.fields.photos_helper') }}</span>
            </div>


            <div class="form-group">
                <button class="btn btn-danger" type="submit">
                    {{ trans('global.save') }}
                </button>
            </div>
        </form>


    </div>
</div>
@endsection

@section('scripts')
<script src="https://maps.googleapis.com/maps/api/js?key={{ env('GOOGLE_MAPS_API_KEY') }}&libraries=places&callback=initialize&language=en&region=GB" async defer></script>
<script src="/js/mapInput.js"></script>
{{--<script>--}}
{{--    var uploadedPhotosMap = {}--}}
{{--Dropzone.options.photosDropzone = {--}}
{{--    url: '{{ route('admin.shops.storeMedia') }}',--}}
{{--    maxFilesize: 2, // MB--}}
{{--    acceptedFiles: '.jpeg,.jpg,.png,.gif',--}}
{{--    addRemoveLinks: true,--}}
{{--    headers: {--}}
{{--      'X-CSRF-TOKEN': "{{ csrf_token() }}"--}}
{{--    },--}}
{{--    params: {--}}
{{--      size: 2,--}}
{{--      width: 4096,--}}
{{--      height: 4096--}}
{{--    },--}}
{{--    success: function (file, response) {--}}
{{--      $('form').append('<input type="hidden" name="photos[]" value="' + response.name + '">')--}}
{{--      uploadedPhotosMap[file.name] = response.name--}}
{{--    },--}}
{{--    removedfile: function (file) {--}}
{{--      console.log(file)--}}
{{--      file.previewElement.remove()--}}
{{--      var name = ''--}}
{{--      if (typeof file.file_name !== 'undefined') {--}}
{{--        name = file.file_name--}}
{{--      } else {--}}
{{--        name = uploadedPhotosMap[file.name]--}}
{{--      }--}}
{{--      $('form').find('input[name="photos[]"][value="' + name + '"]').remove()--}}
{{--    },--}}
{{--    init: function () {--}}
{{--@if(isset($bacon) && $bacon->photos)--}}
{{--      var files =--}}
{{--        {!! json_encode($bacon->photos) !!}--}}
{{--          for (var i in files) {--}}
{{--          var file = files[i]--}}
{{--          this.options.addedfile.call(this, file)--}}
{{--          this.options.thumbnail.call(this, file, file.url)--}}
{{--          file.previewElement.classList.add('dz-complete')--}}
{{--          $('form').append('<input type="hidden" name="photos[]" value="' + file.file_name + '">')--}}
{{--        }--}}
{{--@endif--}}
{{--    },--}}
{{--     error: function (file, response) {--}}
{{--         if ($.type(response) === 'string') {--}}
{{--             var message = response //dropzone sends it's own error messages in string--}}
{{--         } else {--}}
{{--             var message = response.errors.file--}}
{{--         }--}}
{{--         file.previewElement.classList.add('dz-error')--}}
{{--         _ref = file.previewElement.querySelectorAll('[data-dz-errormessage]')--}}
{{--         _results = []--}}
{{--         for (_i = 0, _len = _ref.length; _i < _len; _i++) {--}}
{{--             node = _ref[_i]--}}
{{--             _results.push(node.textContent = message)--}}
{{--         }--}}

{{--         return _results--}}
{{--     }--}}
{{--}--}}
{{--</script>--}}
    </div>
@endsection

resources/views/admin/extra/index.blade.php
@extends('layouts.admin')




@section('content')
    <div class="content">

        <div style="margin-bottom: 10px;" class="row">
            <div class="col-lg-12">
                <a class="btn btn-success" href="{{ route("extra-create") }}">
                    {{ trans('global.add') }} {{ 'Breakfast Extra' }}
                </a>
            </div>
        </div>

        <div class="card">
            <div class="card-header">
                {{ 'Breakfast Extra' }} {{ trans('global.list') }}
            </div>

            <div class="card-body">
                <div class="table-responsive">
                    <table class=" table table-bordered table-striped table-hover datatable datatable-Shop">
                        <thead class=" text-primary">
                        <tr>
                            <th width="10">

                            </th>
{{--                            <th>--}}
{{--                                {{ trans('cruds.shop.fields.id') }}--}}
{{--                            </th>--}}
                            <th>
                                {{ trans('cruds.shop.fields.name') }}
                            </th>
                            <th>
                                {{ 'Description'}}
                            </th>

                            <th>
                                &nbsp;{{ 'Price'}}
                            </th>
                            <th>
                                &nbsp;{{ 'Photos'}}
                            </th>
                            <th>
                            </th>

                        </tr>
                        </thead>
                        <tbody>
                        @foreach($extra as $key => $shop)
                            <tr data-entry-id="{{ $shop->id }}">
                                <td>

                                </td>
{{--                                <td>--}}
{{--                                    {{ $shop->id ?? '' }}--}}
{{--                                </td>--}}
                                <td>
                                    {{ $shop->name ?? '' }}
                                </td>
                                <td>
                                    {{ $shop->description ?? '' }}
                                </td>
                                <td>
                                    {{ $shop->price ?? '' }}
                                </td>
                                <td>

                                </td>
                                <td>
                                    @can('shop_show')
                                        <a class="btn btn-xs btn-primary" href="{{ route('extra-show', $shop->id) }}">
                                            {{ trans('global.view') }}
                                        </a>
                                    @endcan

                                    @can('shop_edit')
                                        <a class="btn btn-xs btn-info" href="{{ route('extra-edit', $shop->id) }}">
                                            {{ trans('global.edit') }}
                                        </a>
                                    @endcan

                                    @can('shop_delete')
                                        <form action="{{ route('extra-delete', $shop->id) }}" method="POST"
                                              onsubmit="return confirm('{{ trans('global.areYouSure') }}');"
                                              style="display: inline-block;">
                                            <input type="hidden" name="_method" value="DELETE">
                                            <input type="hidden" name="_token" value="{{ csrf_token() }}">
                                            <input type="submit" class="btn btn-xs btn-danger"
                                                   value="{{ trans('global.delete') }}">
                                        </form>
                                    @endcan

                                </td>

                            </tr>
                        @endforeach
                        </tbody>
                    </table>

                </div>


            </div>
        </div>
        @endsection
        @section('scripts')
            @parent
            <script>
                $(function () {
                    let dtButtons = $.extend(true, [], $.fn.dataTable.defaults.buttons)
                    @can('shopm_delete')
                    let deleteButtonTrans = '{{ trans('global.datatables.delete') }}'
                    let deleteButton = {
                        text: deleteButtonTrans,
                        url: "{{ route('admin.shops.massDestroy') }}",
                        className: 'btn-danger',
                        action: function (e, dt, node, config) {
                            var ids = $.map(dt.rows({selected: true}).nodes(), function (entry) {
                                return $(entry).data('entry-id')
                            });

                            if (ids.length === 0) {
                                alert('{{ trans('global.datatables.zero_selected') }}')

                                return
                            }

                            if (confirm('{{ trans('global.areYouSure') }}')) {
                                $.ajax({
                                    headers: {'x-csrf-token': _token},
                                    method: 'POST',
                                    url: config.url,
                                    data: {ids: ids, _method: 'DELETE'}
                                })
                                    .done(function () {
                                        location.reload()
                                    })
                            }
                        }
                    }
                    dtButtons.push(deleteButton)
                    @endcan

                    $.extend(true, $.fn.dataTable.defaults, {
                        order: [[1, 'desc']],
                        pageLength: 100,
                    });
                    $('.datatable-Shop:not(.ajaxTable)').DataTable({buttons: dtButtons})
                    $('a[data-toggle="tab"]').on('shown.bs.tab', function (e) {
                        $($.fn.dataTable.tables(true)).DataTable()
                            .columns.adjust();
                    });
                })

            </script>
    </div>
@endsection

resources/views/admin/extra/show.blade.php
@extends('layouts.admin')
@section('content')
    <div class="content">

<div class="card">
    <div class="card-header">
        {{ trans('global.show') }} {{' Breakfast Extra' }}
    </div>

    <div class="card-body">
        <div class="form-group">
            <div class="form-group">
                <a class="btn btn-default" href="{{ route('extra-index') }}">
                    {{ trans('global.back_to_list') }}
                </a>
            </div>
            <table class="table table-bordered table-striped">
                <tbody>
                    <tr>
                        <th>
                            {{ trans('cruds.shop.fields.id') }}
                        </th>
                        <td>
                            {{ $extra->id }}
                        </td>
                    </tr>
                    <tr>
                        <th>
                            {{ trans('cruds.shop.fields.name') }}
                        </th>
                        <td>
                            {{ $extra->name }}
                        </td>
                    </tr>
                    <tr>
                        <th>
                            {{ trans('cruds.shop.fields.description') }}
                        </th>
                        <td>
                            {{ $extra->description }}
                        </td>
                    </tr>
                    <tr>
                        <th>
                            {{ trans('cruds.shop.fields.photos') }}
                        </th>

                    </tr>

                </tbody>
            </table>
            <div class="form-group">
                <a class="btn btn-default" href="{{ route('extra-index') }}">
                    {{ trans('global.back_to_list') }}
                </a>
            </div>
        </div>

    </div>
    </div>
</div>
@endsection