routes/web.php
<?php

//RUN THIS IN PRODUCTION TO CREATE A STORAGE LINK  www.example.com/linkstorage
Route::get('/linkstorage', function () {
    Artisan::call('storage:link');
});


Route::get('/home', function () {
    if (session('status')) {
        return redirect()->route('admin.shops.index')->with('status', session('status'));
    }

    return redirect()->route('admin.shops.index');
});
Route::get('/', function () {
    return view('auth.login');
});
//Route::get('/', 'HomeController@index')->name('home');
Route::get('shop/{shop}', 'HomeController@show')->name('shop');

Auth::routes();

Route::group(['prefix' => 'admin', 'as' => 'admin.', 'namespace' => 'Admin', 'middleware' => ['auth']], function () {
    Route::get('/', 'HomeController@index')->name('home');
    // Permissions
    Route::delete('permissions/destroy', 'PermissionsController@massDestroy')->name('permissions.massDestroy');
    Route::resource('permissions', 'PermissionsController');

    // Roles
    Route::delete('roles/destroy', 'RolesController@massDestroy')->name('roles.massDestroy');
    Route::resource('roles', 'RolesController');

    // Users
    Route::delete('users/destroy', 'UsersController@massDestroy')->name('users.massDestroy');
    Route::resource('users', 'UsersController');

    // Categories
    Route::delete('categories/destroy', 'CategoriesController@massDestroy')->name('categories.massDestroy');
    Route::resource('categories', 'CategoriesController');

    // Shops
    Route::delete('shops/destroy', 'ShopsController@massDestroy')->name('shops.massDestroy');
    Route::post('shops/media', 'ShopsController@storeMedia')->name('shops.storeMedia');
    Route::resource('shops', 'ShopsController');


});


Route::get('page', ['as' => 'page.index',  'uses' => 'DashboardController@index']);

// ADMIN CATEGORY

Route::group(['middleware'=>'permissions:categories'],function (){
   Route::get('/category','Admin\CategoryController@index')->name('admin-cat-index');
});

//SUBCATEGORIES
Route::get('/sub-index', 'Admin\SubCategoriesController@subIndex')->name('sub-index');
Route::get('/sub-create', 'Admin\SubCategoriesController@subCreate')->name('sub-create');
Route::get('show-sub/{category}', 'Admin\SubCategoriesController@subShow')->name('sub-show');
Route::get('edit-sub/{category}', 'Admin\SubCategoriesController@subEdit')->name('sub-edit');
Route::delete('delete-sub/{category}', 'Admin\SubCategoriesController@subDestroy')->name('sub-delete');
Route::post('sub-store', 'Admin\SubCategoriesController@subStore')->name('sub-store');
Route::post('update-sub/{category}', 'Admin\SubCategoriesController@subUpdate')->name('sub-update');
Route::delete('categories/destroy', 'Admin\SubCategoriesController@massDestroy')->name('sub-massDestroy');

Route::post('/subcategory/edit/{id}', 'Admin\SubCategoriesController@update')->name('admin-subcat-update');

//CHILD CATEGORIES
Route::get('/child-index', 'Admin\ChildCategoryController@index')->name('child-index');
Route::get('/child-create', 'Admin\ChildCategoryController@create')->name('child-create');
Route::get('show/{category}', 'Admin\ChildCategoryController@show')->name('child-show');
Route::get('edit/{category}', 'Admin\ChildCategoryController@edit')->name('child-edit');
Route::delete('delete/{category}', 'Admin\ChildCategoryController@destroy')->name('child-delete');
Route::post('store', 'Admin\ChildCategoryController@store')->name('child-store');
Route::post('update/{category}', 'Admin\ChildCategoryController@update')->name('child-update');

Route::get('/bacon-index', 'Admin\BaconController@index')->name('bacon-index');
Route::get('/bacon-create', 'Admin\BaconController@create')->name('bacon-create');
Route::get('show-bacon/{bacon}', 'Admin\BaconController@show')->name('bacon-show');
Route::get('edit-bacon/{bacon}', 'Admin\BaconController@edit')->name('bacon-edit');
Route::delete('delete-bacon/{bacon}', 'Admin\BaconController@destroy')->name('bacon-delete');
Route::post('bacon-store', 'Admin\BaconController@store')->name('bacon-store');
Route::post('update-bac/{bacon}', 'Admin\BaconController@update')->name('bacon-update');

Route::get('/extra-index', 'Admin\BreakfastExtraController@index')->name('extra-index');
Route::get('/extra-create', 'Admin\BreakfastExtraController@create')->name('extra-create');
Route::get('show-extra/{extra}', 'Admin\BreakfastExtraController@show')->name('extra-show');
Route::get('edit-extra/{extra}', 'Admin\BreakfastExtraController@edit')->name('extra-edit');
Route::delete('delete-extra/{extra}', 'Admin\BreakfastExtraController@destroy')->name('extra-delete');
Route::post('extra-store', 'Admin\BreakfastExtraController@store')->name('extra-store');
Route::post('update-extra/{extra}', 'Admin\BreakfastExtraController@update')->name('extra-update');


Route::get('/eggs-index', 'Admin\EggsController@index')->name('eggs-index');
Route::get('/eggs-create', 'Admin\EggsController@create')->name('eggs-create');
Route::get('show-eggs/{eggs}', 'Admin\EggsController@show')->name('eggs-show');
Route::get('edit-eggs/{eggs}', 'Admin\EggsController@edit')->name('eggs-edit');
Route::delete('delete-eggs/{eggs}', 'Admin\EggsController@destroy')->name('eggs-delete');
Route::post('eggs-store', 'Admin\EggsController@store')->name('eggs-store');
Route::post('update-eggs/{eggs}', 'Admin\EggsController@update')->name('eggs-update');

Route::get('/coffee-index', 'Admin\CoffeeController@index')->name('coffee-index');
Route::get('/coffee-create', 'Admin\CoffeeController@create')->name('coffee-create');
Route::get('show-coffee/{coffee}', 'Admin\CoffeeController@show')->name('coffee-show');
Route::get('edit-coffee/{coffee}', 'Admin\CoffeeController@edit')->name('coffee-edit');
Route::delete('delete-coffee/{coffee}', 'Admin\CoffeeController@destroy')->name('coffee-delete');
Route::post('coffee-store', 'Admin\CoffeeController@store')->name('coffee-store');
Route::post('update-coffee/{coffee}', 'Admin\CoffeeController@update')->name('coffee-update');

resources/views/layouts/navbars/auth.blade.php
<div class="sidebar" data-color="white" data-active-color="danger">
    <div class="logo">
        <img src="{{asset('img/logo.png')}}">


    </div>
    <div class="sidebar-wrapper">
        <ul class="nav">
            <li>
                <a href="{{ route('page.index') }}" class="nav-link">
                    <i class="nc-icon nc-bank">

                    </i>
                    {{ trans('cruds.dashboard.title') }}
                </a>
            </li>
            @if(\Illuminate\Support\Facades\Auth::user()->checkAdmin())
                <li>
                    <a href="#menu1" class="accordion-toggle wave-effect" data-toggle="collapse" aria-expanded="false">
                        <i class=""></i>{{ 'User Management' }} <b class="caret"></b>
                    </a>
                    <ul data-toggle="collapse" aria-expanded="false" id="menu1" data-parent="#accordion">
                        <li>
                            <a href="{{ route("admin.users.index") }}"
                               class="nav-link {{ request()->is('admin/users') || request()->is('admin/users/*') ? 'active' : '' }}">

                                {{ trans('cruds.user.title') }}
                            </a>
                        </li>

                    </ul>
                </li>
            @endif

            <li>
                <a href="#menu2" class="accordion-toggle wave-effect" data-toggle="collapse" aria-expanded="false">
                    <i class=""></i>{{ 'Restaurants Management' }} <b class="caret"></b>
                </a>
                <ul data-toggle="collapse" aria-expanded="false" id="menu2" data-parent="#accordion">

                    <li>
                        <a href="{{ route("admin.shops.index") }}"
                           class="nav-link {{ request()->is('admin/shops') || request()->is('admin/shops/*') ? 'active' : '' }}">

                            {{ trans('cruds.shop.title') }}

                        </a>
                    </li>

                </ul>
            </li>


            <li>
                <a href="#menu4" class="accordion-toggle wave-effect" data-toggle="collapse" aria-expanded="false">
                    <i class=""></i>{{ 'Menu Management' }} <b class="caret"></b>
                </a>
                <ul data-toggle="collapse" aria-expanded="false" id="menu4" data-parent="#accordion">

                    <li>
                        <a href="{{ route("admin.categories.index") }}">

                            {{ 'Main Category' }}

                        </a>
                    </li>
                    <li>
                        <a href="{{ route("sub-index") }}">

                            {{ 'Sub Category' }}
                        </a>
                    </li>


                    <li>
                        <a href="{{ route("child-index") }}">

                            {{ 'Child Category' }}

                        </a>
                    </li>

                </ul>
            </li>

            @if(\Illuminate\Support\Facades\Auth::user()->checkManager()||\Illuminate\Support\Facades\Auth::user()->checkStaff())
                <li>
                    <a href="#menu3" class="accordion-toggle wave-effect" data-toggle="collapse" aria-expanded="false">
                        <i class=""></i>{{ 'Staff Management' }} <b class="caret"></b>
                    </a>
                    <ul data-toggle="collapse" aria-expanded="false" id="menu3" data-parent="#accordion">

                        <li>
                            <a href="{{ route("admin.users.index") }}"
                               class="nav-link {{ request()->is('admin/users') || request()->is('admin/users/*') ? 'active' : '' }}">

                                {{ 'Staff' }}
                            </a>
                        </li>

                    </ul>
                </li>
            @endif

        </ul>
    </div>
</div>

resources/views/layouts/navbars/fixed-plugin-js.blade.php
<script>
    $(document).ready(function () {
        $('#facebook').sharrre({
            share: {
                facebook: true
            },
            enableHover: false,
            enableTracking: false,
            enableCounter: false,
            click: function (api, options) {
                api.simulateClick();
                api.openPopup('facebook');
            },
            template: '<i class="fab fa-facebook-f"></i> Facebook',
            url: 'https://demos.creative-tim.com/paper-dashboard/examples/dashboard.html'
        });
        $('#google').sharrre({
            share: {
                googlePlus: true
            },
            enableCounter: false,
            enableHover: false,
            enableTracking: true,
            click: function (api, options) {
                api.simulateClick();
                api.openPopup('googlePlus');
            },
            template: '<i class="fab fa-google-plus"></i> Google',
            url: 'https://demos.creative-tim.com/paper-dashboard/examples/dashboard.html'
        });
        $('#twitter').sharrre({
            share: {
                twitter: true
            },
            enableHover: false,
            enableTracking: false,
            enableCounter: false,
            buttons: {
                twitter: {
                    via: 'CreativeTim'
                }
            },
            click: function (api, options) {
                api.simulateClick();
                api.openPopup('twitter');
            },
            template: '<i class="fab fa-twitter"></i> Twitter',
            url: 'https://demos.creative-tim.com/paper-dashboard/examples/dashboard.html'
        });
        // Facebook Pixel Code Don't Delete
        ! function (f, b, e, v, n, t, s) {
            if (f.fbq) return;
            n = f.fbq = function () {
                n.callMethod ?
                    n.callMethod.apply(n, arguments) : n.queue.push(arguments)
            };
            if (!f._fbq) f._fbq = n;
            n.push = n;
            n.loaded = !0;
            n.version = '2.0';
            n.queue = [];
            t = b.createElement(e);
            t.async = !0;
            t.src = v;
            s = b.getElementsByTagName(e)[0];
            s.parentNode.insertBefore(t, s)
        }(window,
            document, 'script', '//connect.facebook.net/en_US/fbevents.js');
        try {
            fbq('init', '111649226022273');
            fbq('track', "PageView");
        } catch (err) {
            console.log('Facebook Track Error:', err);
        }
    });
</script>
<script>
    $(document).ready(function () {
        $sidebar = $('.sidebar');
        $sidebar_img_container = $sidebar.find('.sidebar-background');
        $full_page = $('.full-page');
        $sidebar_responsive = $('body > .navbar-collapse');
        sidebar_mini_active = true;
        window_width = $(window).width();
        fixed_plugin_open = $('.sidebar .sidebar-wrapper .nav li.active a p').html();
        // if( window_width > 767 && fixed_plugin_open == 'Dashboard' ){
        //     if($('.fixed-plugin .dropdown').hasClass('show-dropdown')){
        //         $('.fixed-plugin .dropdown').addClass('show');
        //     }
        //
        // }
        $('.fixed-plugin a').click(function (event) {
            // Alex if we click on switch, stop propagation of the event, so the dropdown will not be hide, otherwise we set the  section active
            if ($(this).hasClass('switch-trigger')) {
                if (event.stopPropagation) {
                    event.stopPropagation();
                } else if (window.event) {
                    window.event.cancelBubble = true;
                }
            }
        });
        $('.fixed-plugin .active-color span').click(function () {
            $full_page_background = $('.full-page-background');
            $(this).siblings().removeClass('active');
            $(this).addClass('active');
            var new_color = $(this).data('color');
            if ($sidebar.length != 0) {
                $sidebar.attr('data-active-color', new_color);
            }
            if ($full_page.length != 0) {
                $full_page.attr('data-active-color', new_color);
            }
            if ($sidebar_responsive.length != 0) {
                $sidebar_responsive.attr('data-active-color', new_color);
            }
        });
        $('.fixed-plugin .background-color span').click(function () {
            $(this).siblings().removeClass('active');
            $(this).addClass('active');
            var new_color = $(this).data('color');
            if ($sidebar.length != 0) {
                $sidebar.attr('data-color', new_color);
            }
            if ($full_page.length != 0) {
                $full_page.attr('filter-color', new_color);
            }
            if ($sidebar_responsive.length != 0) {
                $sidebar_responsive.attr('data-color', new_color);
            }
        });
        $('.fixed-plugin .img-holder').click(function () {
            $full_page_background = $('.full-page-background');
            $(this).parent('li').siblings().removeClass('active');
            $(this).parent('li').addClass('active');
            var new_image = $(this).find("img").attr('src');
            if ($sidebar_img_container.length != 0 && $('.switch-sidebar-image input:checked').length != 0) {
                $sidebar_img_container.fadeOut('fast', function () {
                    $sidebar_img_container.css('background-image', 'url("' + new_image + '")');
                    $sidebar_img_container.fadeIn('fast');
                });
            }
            if ($full_page_background.length != 0 && $('.switch-sidebar-image input:checked').length != 0) {
                var new_image_full_page = $('.fixed-plugin li.active .img-holder').find('img').data('src');
                $full_page_background.fadeOut('fast', function () {
                    $full_page_background.css('background-image', 'url("' + new_image_full_page + '")');
                    $full_page_background.fadeIn('fast');
                });
            }
            if ($('.switch-sidebar-image input:checked').length == 0) {
                var new_image = $('.fixed-plugin li.active .img-holder').find("img").attr('src');
                var new_image_full_page = $('.fixed-plugin li.active .img-holder').find('img').data('src');
                $sidebar_img_container.css('background-image', 'url("' + new_image + '")');
                $full_page_background.css('background-image', 'url("' + new_image_full_page + '")');
            }
            if ($sidebar_responsive.length != 0) {
                $sidebar_responsive.css('background-image', 'url("' + new_image + '")');
            }
        });
        $('.switch-sidebar-image input').on("switchChange.bootstrapSwitch", function () {
            $full_page_background = $('.full-page-background');
            $input = $(this);
            if ($input.is(':checked')) {
                if ($sidebar_img_container.length != 0) {
                    $sidebar_img_container.fadeIn('fast');
                    $sidebar.attr('data-image', '#');
                }
                if ($full_page_background.length != 0) {
                    $full_page_background.fadeIn('fast');
                    $full_page.attr('data-image', '#');
                }
                background_image = true;
            } else {
                if ($sidebar_img_container.length != 0) {
                    $sidebar.removeAttr('data-image');
                    $sidebar_img_container.fadeOut('fast');
                }
                if ($full_page_background.length != 0) {
                    $full_page.removeAttr('data-image', '#');
                    $full_page_background.fadeOut('fast');
                }
                background_image = false;
            }
        });
        $('.switch-mini input').on("switchChange.bootstrapSwitch", function () {
            $body = $('body');
            $input = $(this);
            if (paperDashboard.misc.sidebar_mini_active == true) {
                $('body').removeClass('sidebar-mini');
                paperDashboard.misc.sidebar_mini_active = false;
                $('.sidebar .sidebar-wrapper, .main-panel').perfectScrollbar();
            } else {
                $('.sidebar .sidebar-wrapper, .main-panel').perfectScrollbar('destroy');
                setTimeout(function () {
                    $('body').addClass('sidebar-mini');
                    paperDashboard.misc.sidebar_mini_active = true;
                }, 300);
            }
            // we simulate the window Resize so the charts will get updated in realtime.
            var simulateWindowResize = setInterval(function () {
                window.dispatchEvent(new Event('resize'));
            }, 180);
            // we stop the simulation of Window Resize after the animations are completed
            setTimeout(function () {
                clearInterval(simulateWindowResize);
            }, 1000);
        });
    });
</script>

resources/views/layouts/navbars/fixed-plugin.blade.php
<div class="fixed-plugin">
    <div class="dropdown show-dropdown">
        <a href="#" data-toggle="dropdown">
            <i class="fa fa-cog fa-2x"> </i>
        </a>
        <ul class="dropdown-menu">
            <li class="header-title"> Sidebar Background</li>
            <li class="adjustments-line">
                <a href="javascript:void(0)" class="switch-trigger background-color">
                    <div class="badge-colors text-center">
                        <span class="badge filter badge-light active" data-color="white"></span>
                        <span class="badge filter badge-dark" data-color="black"></span>
                    </div>
                    <div class="clearfix"></div>
                </a>
            </li>
            <li class="header-title"> Sidebar Active Color</li>
            <li class="adjustments-line text-center">
                <a href="javascript:void(0)" class="switch-trigger active-color">
                    <span class="badge filter badge-primary" data-color="primary"></span>
                    <span class="badge filter badge-info" data-color="info"></span>
                    <span class="badge filter badge-success" data-color="success"></span>
                    <span class="badge filter badge-warning" data-color="warning"></span>
                    <span class="badge filter badge-danger active" data-color="danger"></span>
                </a>
            </li>
            <li class="button-container">
                <a href="https://www.creative-tim.com/product/paper-dashboard-laravel" target="_blank"
                    class="btn btn-primary btn-block btn-round">Download Now</a>
            </li>
            <li class="button-container">
                <a href="https://paper-dashboard-laravel.creative-tim.com/docs/getting-started/laravel-setup.html"
                    target="_blank" class="btn btn-outline-default btn-block btn-round">
                    <i class="nc-icon nc-paper"></i> Documentation
                </a>
            </li>
            <li class="header-title">
                Want more components?
            </li>
            <li class="button-container">
                <a href="https://www.creative-tim.com/product/paper-dashboard-pro-laravel" target="_blank"
                    class="btn btn-danger btn-block btn-round">
                    Get Pro Version
                </a>
            </li>
            <li class="header-title">Thank you for 95 shares!</li>
            <li class="button-container text-center">
                <button id="twitter" class="btn btn-outline-default btn-round btn-sm"><i class="fa fa-twitter"></i>
                    &middot; 45</button>
                <button id="facebook" class="btn btn-outline-default btn-round btn-sm"><i class="fa fa-facebook-f"></i>
                    &middot; 50</button>
                <br>
                <br>
                <a class="github-button" href="https://github.com/creativetimofficial/paper-dashboard"
                    data-icon="octicon-star" data-size="large" data-show-count="true"
                    aria-label="Star ntkme/github-buttons on GitHub">Star</a>
            </li>
        </ul>
    </div>
</div>