routes/web.php
<?php

//RUN THIS IN PRODUCTION TO CREATE A STORAGE LINK  www.example.com/linkstorage
Route::get('/linkstorage', function () {
    Artisan::call('storage:link');
});


Route::get('/home', function () {
    if (session('status')) {
        return redirect()->route('admin.shops.index')->with('status', session('status'));
    }

    return redirect()->route('admin.shops.index');
});
Route::get('/', function () {
    return view('auth.login');
});
//Route::get('/', 'HomeController@index')->name('home');
Route::get('shop/{shop}', 'HomeController@show')->name('shop');

Auth::routes();

Route::group(['prefix' => 'admin', 'as' => 'admin.', 'namespace' => 'Admin', 'middleware' => ['auth']], function () {
    Route::get('/', 'HomeController@index')->name('home');
    // Permissions
    Route::delete('permissions/destroy', 'PermissionsController@massDestroy')->name('permissions.massDestroy');
    Route::resource('permissions', 'PermissionsController');

    // Roles
    Route::delete('roles/destroy', 'RolesController@massDestroy')->name('roles.massDestroy');
    Route::resource('roles', 'RolesController');

    // Users
    Route::delete('users/destroy', 'UsersController@massDestroy')->name('users.massDestroy');
    Route::resource('users', 'UsersController');

    // Categories
    Route::delete('categories/destroy', 'CategoriesController@massDestroy')->name('categories.massDestroy');
    Route::resource('categories', 'CategoriesController');

    // Shops
    Route::delete('shops/destroy', 'ShopsController@massDestroy')->name('shops.massDestroy');
    Route::post('shops/media', 'ShopsController@storeMedia')->name('shops.storeMedia');
    Route::resource('shops', 'ShopsController');


});


Route::get('page', ['as' => 'page.index',  'uses' => 'DashboardController@index']);

// ADMIN CATEGORY

Route::group(['middleware'=>'permissions:categories'],function (){
   Route::get('/category','Admin\CategoryController@index')->name('admin-cat-index');
});

//SUBCATEGORIES
Route::get('/sub-index', 'Admin\SubCategoriesController@subIndex')->name('sub-index');
Route::get('/sub-create', 'Admin\SubCategoriesController@subCreate')->name('sub-create');
Route::get('show-sub/{category}', 'Admin\SubCategoriesController@subShow')->name('sub-show');
Route::get('edit-sub/{category}', 'Admin\SubCategoriesController@subEdit')->name('sub-edit');
Route::delete('delete-sub/{category}', 'Admin\SubCategoriesController@subDestroy')->name('sub-delete');
Route::post('sub-store', 'Admin\SubCategoriesController@subStore')->name('sub-store');
Route::post('update-sub/{category}', 'Admin\SubCategoriesController@subUpdate')->name('sub-update');
Route::delete('categories/destroy', 'Admin\SubCategoriesController@massDestroy')->name('sub-massDestroy');

Route::post('/subcategory/edit/{id}', 'Admin\SubCategoriesController@update')->name('admin-subcat-update');

//CHILD CATEGORIES
Route::get('/child-index', 'Admin\ChildCategoryController@index')->name('child-index');
Route::get('/child-create', 'Admin\ChildCategoryController@create')->name('child-create');
Route::get('show/{category}', 'Admin\ChildCategoryController@show')->name('child-show');
Route::get('edit/{category}', 'Admin\ChildCategoryController@edit')->name('child-edit');
Route::delete('delete/{category}', 'Admin\ChildCategoryController@destroy')->name('child-delete');
Route::post('store', 'Admin\ChildCategoryController@store')->name('child-store');
Route::post('update/{category}', 'Admin\ChildCategoryController@update')->name('child-update');

Route::get('/bacon-index', 'Admin\BaconController@index')->name('bacon-index');
Route::get('/bacon-create', 'Admin\BaconController@create')->name('bacon-create');
Route::get('show-bacon/{bacon}', 'Admin\BaconController@show')->name('bacon-show');
Route::get('edit-bacon/{bacon}', 'Admin\BaconController@edit')->name('bacon-edit');
Route::delete('delete-bacon/{bacon}', 'Admin\BaconController@destroy')->name('bacon-delete');
Route::post('bacon-store', 'Admin\BaconController@store')->name('bacon-store');
Route::post('update-bac/{bacon}', 'Admin\BaconController@update')->name('bacon-update');

Route::get('/extra-index', 'Admin\BreakfastExtraController@index')->name('extra-index');
Route::get('/extra-create', 'Admin\BreakfastExtraController@create')->name('extra-create');
Route::get('show-extra/{extra}', 'Admin\BreakfastExtraController@show')->name('extra-show');
Route::get('edit-extra/{extra}', 'Admin\BreakfastExtraController@edit')->name('extra-edit');
Route::delete('delete-extra/{extra}', 'Admin\BreakfastExtraController@destroy')->name('extra-delete');
Route::post('extra-store', 'Admin\BreakfastExtraController@store')->name('extra-store');
Route::post('update-extra/{extra}', 'Admin\BreakfastExtraController@update')->name('extra-update');


Route::get('/eggs-index', 'Admin\EggsController@index')->name('eggs-index');
Route::get('/eggs-create', 'Admin\EggsController@create')->name('eggs-create');
Route::get('show-eggs/{eggs}', 'Admin\EggsController@show')->name('eggs-show');
Route::get('edit-eggs/{eggs}', 'Admin\EggsController@edit')->name('eggs-edit');
Route::delete('delete-eggs/{eggs}', 'Admin\EggsController@destroy')->name('eggs-delete');
Route::post('eggs-store', 'Admin\EggsController@store')->name('eggs-store');
Route::post('update-eggs/{eggs}', 'Admin\EggsController@update')->name('eggs-update');

Route::get('/coffee-index', 'Admin\CoffeeController@index')->name('coffee-index');
Route::get('/coffee-create', 'Admin\CoffeeController@create')->name('coffee-create');
Route::get('show-coffee/{coffee}', 'Admin\CoffeeController@show')->name('coffee-show');
Route::get('edit-coffee/{coffee}', 'Admin\CoffeeController@edit')->name('coffee-edit');
Route::delete('delete-coffee/{coffee}', 'Admin\CoffeeController@destroy')->name('coffee-delete');
Route::post('coffee-store', 'Admin\CoffeeController@store')->name('coffee-store');
Route::post('update-coffee/{coffee}', 'Admin\CoffeeController@update')->name('coffee-update');

app/Category.php
<?php

namespace App;

use Illuminate\Database\Eloquent\Model;
use Illuminate\Database\Eloquent\SoftDeletes;

class Category extends Model
{
    use SoftDeletes;

    public $table = 'categories';

    protected $dates = [
        'created_at',
        'updated_at',
        'deleted_at',
    ];

    protected $fillable = [
        'name',
        'created_at',
        'updated_at',
        'deleted_at',
    ];

    public function shops()
    {
        return $this->belongsToMany(Shop::class);
    }
}

app/Http/Controllers/Admin/CategoriesController.php
<?php

namespace App\Http\Controllers\Admin;

use App\Category;
use App\Http\Controllers\Controller;
use App\Http\Requests\MassDestroyCategoryRequest;
use App\Http\Requests\StoreCategoryRequest;
use App\Http\Requests\UpdateCategoryRequest;
use Gate;
use Illuminate\Http\Request;
use Symfony\Component\HttpFoundation\Response;

class CategoriesController extends Controller
{
    public function index()
    {
//        abort_if(Gate::denies('category_access'), Response::HTTP_FORBIDDEN, '403 Forbidden');

        $categories = Category::all();

        return view('admin.categories.index', compact('categories'));
    }

    public function subIndex()
    {
//        abort_if(Gate::denies('category_access'), Response::HTTP_FORBIDDEN, '403 Forbidden');

        $subcategories = Category::all();

        return view('admin.subcategories.index', compact('subcategories'));
    }

    public function create()
    {
        abort_if(Gate::denies('category_create'), Response::HTTP_FORBIDDEN, '403 Forbidden');

        return view('admin.categories.create');
    }
    public function subCreate()
    {
//        abort_if(Gate::denies('category_create'), Response::HTTP_FORBIDDEN, '403 Forbidden');

        return view('admin.subcategories.create');
    }

    public function store(StoreCategoryRequest $request)
    {
        $category = Category::create($request->all());

        return redirect()->route('admin.categories.index');
    }
    public function subStore(StoreCategoryRequest $request)
    {
        $category = Category::create($request->all());

        return redirect()->route('admin.subcategories.index');
    }

    public function edit(Category $category)
    {
        abort_if(Gate::denies('category_edit'), Response::HTTP_FORBIDDEN, '403 Forbidden');

        return view('admin.categories.edit', compact('category'));
    }
    public function subEdit(Category $category)
    {
//        abort_if(Gate::denies('category_edit'), Response::HTTP_FORBIDDEN, '403 Forbidden');

        return view('admin.subcategories.edit', compact('category'));
    }

    public function update(UpdateCategoryRequest $request, Category $category)
    {
        $category->update($request->all());

        return redirect()->route('admin.categories.index');
    }
    public function subUpdate(UpdateCategoryRequest $request, Category $category)
    {
        $category->update($request->all());

        return redirect()->route('admin.subcategories.index');
    }

    public function show(Category $category)
    {
        abort_if(Gate::denies('category_show'), Response::HTTP_FORBIDDEN, '403 Forbidden');

        return view('admin.categories.show', compact('category'));
    }

    public function subShow(Category $category)
    {
//        abort_if(Gate::denies('category_show'), Response::HTTP_FORBIDDEN, '403 Forbidden');

        return view('admin.subcategories.show', compact('category'));
    }

    public function destroy(Category $category)
    {
        abort_if(Gate::denies('category_delete'), Response::HTTP_FORBIDDEN, '403 Forbidden');

        $category->delete();

        return back();
    }
    public function subDestroy(Category $category)
    {
//        abort_if(Gate::denies('category_delete'), Response::HTTP_FORBIDDEN, '403 Forbidden');

        $category->delete();

        return back();
    }

    public function massDestroy(MassDestroyCategoryRequest $request)
    {
        Category::whereIn('id', request('ids'))->delete();

        return response(null, Response::HTTP_NO_CONTENT);
    }

    public function subMassDestroy(MassDestroyCategoryRequest $request)
    {
        Category::whereIn('id', request('ids'))->delete();

        return response(null, Response::HTTP_NO_CONTENT);
    }
}

resources/views/admin/categories/create.blade.php
@extends('layouts.dash', [
    'class' => '',
    'elementActive' => 'permission'
])
@section('content')
<div class="content">
<div class="card">
    <div class="card-header">
        {{ trans('global.create') }} {{ trans('cruds.category.title_singular') }}
    </div>

    <div class="card-body">
        <form method="POST" action="{{ route("admin.categories.store") }}" enctype="multipart/form-data">
            @csrf
            <div class="form-group">
                <label class="required" for="name">{{ trans('cruds.category.fields.name') }}</label>
                <input class="form-control {{ $errors->has('name') ? 'is-invalid' : '' }}" type="text" name="name" id="name" value="{{ old('name', '') }}" required>
                @if($errors->has('name'))
                    <div class="invalid-feedback">
                        {{ $errors->first('name') }}
                    </div>
                @endif
                <span class="help-block">{{ trans('cruds.category.fields.name_helper') }}</span>
            </div>
            <div class="form-group">
                <button class="btn btn-danger" type="submit">
                    {{ trans('global.save') }}
                </button>
            </div>
        </form>


    </div>
</div>
</div>
@endsection

resources/views/admin/categories/edit.blade.php
@extends('layouts.dash', [
    'class' => '',
    'elementActive' => 'permission'
])
@section('content')
    <div class="content">

<div class="card">
    <div class="card-header">
        {{ trans('global.edit') }} {{ trans('cruds.category.title_singular') }}
    </div>

    <div class="card-body">
        <form method="POST" action="{{ route("admin.categories.update", [$category->id]) }}" enctype="multipart/form-data">
            @method('PUT')
            @csrf
            <div class="form-group">
                <label class="required" for="name">{{ trans('cruds.category.fields.name') }}</label>
                <input class="form-control {{ $errors->has('name') ? 'is-invalid' : '' }}" type="text" name="name" id="name" value="{{ old('name', $category->name) }}" required>
                @if($errors->has('name'))
                    <div class="invalid-feedback">
                        {{ $errors->first('name') }}
                    </div>
                @endif
                <span class="help-block">{{ trans('cruds.category.fields.name_helper') }}</span>
            </div>
            <div class="form-group">
                <button class="btn btn-danger" type="submit">
                    {{ trans('global.save') }}
                </button>
            </div>
        </form>


    </div>
</div>
    </div>
@endsection

resources/views/admin/categories/index.blade.php
@extends('layouts.admin')


@section('content')
    <div class="content">
        @can('category_create')
            <div style="margin-bottom: 10px;" class="row">
                <div class="col-lg-12">
                    <a class="btn btn-success" href="{{ route("admin.categories.create") }}">
                        {{ trans('global.add') }} {{ trans('cruds.category.title_singular') }}
                    </a>
                </div>
            </div>
        @endcan
        <div class="card">
            <div class="card-header">
                {{ trans('cruds.category.title_singular') }} {{ trans('global.list') }}
            </div>

            <div class="card-body">
                <div class="table-responsive">
                    <table class=" table table-bordered table-striped table-hover datatable datatable-Category">
                        <thead>
                        <tr>
                            <th width="10">

                            </th>
                            <th>
                                {{ trans('cruds.category.fields.id') }}
                            </th>
                            <th>
                                {{ trans('cruds.category.fields.name') }}
                            </th>
                            <th>
                                &nbsp;
                            </th>
                        </tr>
                        </thead>
                        <tbody>
                        @foreach($categories as $key => $category)
                            <tr data-entry-id="{{ $category->id }}">
                                <td>

                                </td>
                                <td>
                                    {{ $category->id ?? '' }}
                                </td>
                                <td>
                                    {{ $category->name ?? '' }}
                                </td>
                                <td>
                                    @can('category_show')
                                        <a class="btn btn-xs btn-primary"
                                           href="{{ route('admin.categories.show', $category->id) }}">
                                            {{ trans('global.view') }}
                                        </a>
                                    @endcan

                                    @can('category_edit')
                                        <a class="btn btn-xs btn-info"
                                           href="{{ route('admin.categories.edit', $category->id) }}">
                                            {{ trans('global.edit') }}
                                        </a>
                                    @endcan

                                    @can('category_delete')
                                        <form action="{{ route('admin.categories.destroy', $category->id) }}"
                                              method="POST"
                                              onsubmit="return confirm('{{ trans('global.areYouSure') }}');"
                                              style="display: inline-block;">
                                            <input type="hidden" name="_method" value="DELETE">
                                            <input type="hidden" name="_token" value="{{ csrf_token() }}">
                                            <input type="submit" class="btn btn-xs btn-danger"
                                                   value="{{ trans('global.delete') }}">
                                        </form>
                                    @endcan

                                </td>

                            </tr>
                        @endforeach
                        </tbody>
                    </table>
                </div>


            </div>
        </div>
        @endsection
        @section('scripts')
            @parent
            <script>
                $(function () {
                    let dtButtons = $.extend(true, [], $.fn.dataTable.defaults.buttons)
                    @can('category_delete')
                    let deleteButtonTrans = '{{ trans('global.datatables.delete') }}'
                    let deleteButton = {
                        text: deleteButtonTrans,
                        url: "{{ route('admin.categories.massDestroy') }}",
                        className: 'btn-danger',
                        action: function (e, dt, node, config) {
                            var ids = $.map(dt.rows({selected: true}).nodes(), function (entry) {
                                return $(entry).data('entry-id')
                            });

                            if (ids.length === 0) {
                                alert('{{ trans('global.datatables.zero_selected') }}')

                                return
                            }

                            if (confirm('{{ trans('global.areYouSure') }}')) {
                                $.ajax({
                                    headers: {'x-csrf-token': _token},
                                    method: 'POST',
                                    url: config.url,
                                    data: {ids: ids, _method: 'DELETE'}
                                })
                                    .done(function () {
                                        location.reload()
                                    })
                            }
                        }
                    }
                    dtButtons.push(deleteButton)
                    @endcan

                    $.extend(true, $.fn.dataTable.defaults, {
                        order: [[1, 'desc']],
                        pageLength: 100,
                    });
                    $('.datatable-Category:not(.ajaxTable)').DataTable({buttons: dtButtons})
                    $('a[data-toggle="tab"]').on('shown.bs.tab', function (e) {
                        $($.fn.dataTable.tables(true)).DataTable()
                            .columns.adjust();
                    });
                })

            </script>
    </div>
@endsection

resources/views/admin/categories/show.blade.php
@extends('layouts.dash', [
    'class' => '',
    'elementActive' => 'permission'
])
@section('content')
    <div class="content">

<div class="card">
    <div class="card-header">
        {{ trans('global.show') }} {{ trans('cruds.category.title') }}
    </div>

    <div class="card-body">
        <div class="form-group">
            <div class="form-group">
                <a class="btn btn-default" href="{{ route('admin.categories.index') }}">
                    {{ trans('global.back_to_list') }}
                </a>
            </div>
            <table class="table table-bordered table-striped">
                <tbody>
                    <tr>
                        <th>
                            {{ trans('cruds.category.fields.id') }}
                        </th>
                        <td>
                            {{ $category->id }}
                        </td>
                    </tr>
                    <tr>
                        <th>
                            {{ trans('cruds.category.fields.name') }}
                        </th>
                        <td>
                            {{ $category->name }}
                        </td>
                    </tr>
                </tbody>
            </table>
            <div class="form-group">
                <a class="btn btn-default" href="{{ route('admin.categories.index') }}">
                    {{ trans('global.back_to_list') }}
                </a>
            </div>
        </div>


    </div>
</div>
    </div>
@endsection