routes/web.php
<?php

//RUN THIS IN PRODUCTION TO CREATE A STORAGE LINK  www.example.com/linkstorage
Route::get('/linkstorage', function () {
    Artisan::call('storage:link');
});


Route::get('/home', function () {
    if (session('status')) {
        return redirect()->route('admin.shops.index')->with('status', session('status'));
    }

    return redirect()->route('admin.shops.index');
});
Route::get('/', function () {
    return view('auth.login');
});
//Route::get('/', 'HomeController@index')->name('home');
Route::get('shop/{shop}', 'HomeController@show')->name('shop');

Auth::routes();

Route::group(['prefix' => 'admin', 'as' => 'admin.', 'namespace' => 'Admin', 'middleware' => ['auth']], function () {
    Route::get('/', 'HomeController@index')->name('home');
    // Permissions
    Route::delete('permissions/destroy', 'PermissionsController@massDestroy')->name('permissions.massDestroy');
    Route::resource('permissions', 'PermissionsController');

    // Roles
    Route::delete('roles/destroy', 'RolesController@massDestroy')->name('roles.massDestroy');
    Route::resource('roles', 'RolesController');

    // Users
    Route::delete('users/destroy', 'UsersController@massDestroy')->name('users.massDestroy');
    Route::resource('users', 'UsersController');

    // Categories
    Route::delete('categories/destroy', 'CategoriesController@massDestroy')->name('categories.massDestroy');
    Route::resource('categories', 'CategoriesController');

    // Shops
    Route::delete('shops/destroy', 'ShopsController@massDestroy')->name('shops.massDestroy');
    Route::post('shops/media', 'ShopsController@storeMedia')->name('shops.storeMedia');
    Route::resource('shops', 'ShopsController');


});


Route::get('page', ['as' => 'page.index',  'uses' => 'DashboardController@index']);

// ADMIN CATEGORY

Route::group(['middleware'=>'permissions:categories'],function (){
   Route::get('/category','Admin\CategoryController@index')->name('admin-cat-index');
});

//SUBCATEGORIES
Route::get('/sub-index', 'Admin\SubCategoriesController@subIndex')->name('sub-index');
Route::get('/sub-create', 'Admin\SubCategoriesController@subCreate')->name('sub-create');
Route::get('show-sub/{category}', 'Admin\SubCategoriesController@subShow')->name('sub-show');
Route::get('edit-sub/{category}', 'Admin\SubCategoriesController@subEdit')->name('sub-edit');
Route::delete('delete-sub/{category}', 'Admin\SubCategoriesController@subDestroy')->name('sub-delete');
Route::post('sub-store', 'Admin\SubCategoriesController@subStore')->name('sub-store');
Route::post('update-sub/{category}', 'Admin\SubCategoriesController@subUpdate')->name('sub-update');
Route::delete('categories/destroy', 'Admin\SubCategoriesController@massDestroy')->name('sub-massDestroy');

Route::post('/subcategory/edit/{id}', 'Admin\SubCategoriesController@update')->name('admin-subcat-update');

//CHILD CATEGORIES
Route::get('/child-index', 'Admin\ChildCategoryController@index')->name('child-index');
Route::get('/child-create', 'Admin\ChildCategoryController@create')->name('child-create');
Route::get('show/{category}', 'Admin\ChildCategoryController@show')->name('child-show');
Route::get('edit/{category}', 'Admin\ChildCategoryController@edit')->name('child-edit');
Route::delete('delete/{category}', 'Admin\ChildCategoryController@destroy')->name('child-delete');
Route::post('store', 'Admin\ChildCategoryController@store')->name('child-store');
Route::post('update/{category}', 'Admin\ChildCategoryController@update')->name('child-update');

Route::get('/bacon-index', 'Admin\BaconController@index')->name('bacon-index');
Route::get('/bacon-create', 'Admin\BaconController@create')->name('bacon-create');
Route::get('show-bacon/{bacon}', 'Admin\BaconController@show')->name('bacon-show');
Route::get('edit-bacon/{bacon}', 'Admin\BaconController@edit')->name('bacon-edit');
Route::delete('delete-bacon/{bacon}', 'Admin\BaconController@destroy')->name('bacon-delete');
Route::post('bacon-store', 'Admin\BaconController@store')->name('bacon-store');
Route::post('update-bac/{bacon}', 'Admin\BaconController@update')->name('bacon-update');

Route::get('/extra-index', 'Admin\BreakfastExtraController@index')->name('extra-index');
Route::get('/extra-create', 'Admin\BreakfastExtraController@create')->name('extra-create');
Route::get('show-extra/{extra}', 'Admin\BreakfastExtraController@show')->name('extra-show');
Route::get('edit-extra/{extra}', 'Admin\BreakfastExtraController@edit')->name('extra-edit');
Route::delete('delete-extra/{extra}', 'Admin\BreakfastExtraController@destroy')->name('extra-delete');
Route::post('extra-store', 'Admin\BreakfastExtraController@store')->name('extra-store');
Route::post('update-extra/{extra}', 'Admin\BreakfastExtraController@update')->name('extra-update');


Route::get('/eggs-index', 'Admin\EggsController@index')->name('eggs-index');
Route::get('/eggs-create', 'Admin\EggsController@create')->name('eggs-create');
Route::get('show-eggs/{eggs}', 'Admin\EggsController@show')->name('eggs-show');
Route::get('edit-eggs/{eggs}', 'Admin\EggsController@edit')->name('eggs-edit');
Route::delete('delete-eggs/{eggs}', 'Admin\EggsController@destroy')->name('eggs-delete');
Route::post('eggs-store', 'Admin\EggsController@store')->name('eggs-store');
Route::post('update-eggs/{eggs}', 'Admin\EggsController@update')->name('eggs-update');

Route::get('/coffee-index', 'Admin\CoffeeController@index')->name('coffee-index');
Route::get('/coffee-create', 'Admin\CoffeeController@create')->name('coffee-create');
Route::get('show-coffee/{coffee}', 'Admin\CoffeeController@show')->name('coffee-show');
Route::get('edit-coffee/{coffee}', 'Admin\CoffeeController@edit')->name('coffee-edit');
Route::delete('delete-coffee/{coffee}', 'Admin\CoffeeController@destroy')->name('coffee-delete');
Route::post('coffee-store', 'Admin\CoffeeController@store')->name('coffee-store');
Route::post('update-coffee/{coffee}', 'Admin\CoffeeController@update')->name('coffee-update');

resources/views/pages/allusers.blade.php
@extends('layouts.app', [
    'class' => '',
    'elementActive' => 'allusers'
])


@section('content')
    <div class="content">
        <div class="row">
            <div class="col-md-12">
                <div class="card">
                    <div class="card-header">
                        <i class="nc-icon"><img src="{{ asset('paper/img/user-profile.png') }}"></i> User
                        <a href="{{ route('page.index', 'creates') }}" class="btn btn-success btn-sm float-right"><i
                                class="fas fa-plus"></i> Create User</a>
                    </div>
                    <div class="card-body">
                        <div class="table-responsive">

                            <table>
                                <thead>
                                <tr>
                                    <th scope="col">ID</th>
                                    <th scope="col">Name</th>
                                    <th scope="col">Role</th>
                                    <th scope="col">Email</th>
                                    <th scope="col">Edit</th>
                                    <th scope="col">Delete</th>
                                </tr>
                                </thead>
                                <tbody>
                                @foreach(\App\Models\User::all() as $user)
                                    <tr>
                                        <td>{{$user->id}}</td>
                                        <td>{{$user->name}}</td>
                                        <td>{{$user->role}}</td>
                                        <td>{{$user->email}}</td>
                                        <td><a href="{{ route('user.users') }}" class="btn btn-warning">Edit</a></td>
                                        <td>
                                            <form action="/management/user/{{$user->id}}" method="post">
                                                @csrf
                                                @method('DELETE')
                                                <input type="submit" value="Delete" class="btn btn-danger">
                                            </form>
                                        </td>
                                    </tr>
                                @endforeach
                                </tbody>
                            </table>

                        </div>
                    </div>
                </div>
            </div>

        </div>
    </div>
@endsection

resources/views/pages/creates.blade.php
@extends('layouts.app', [
    'class' => '',
    'elementActive' => 'creates'
])

@section('content')
    <div class="container">

        <div class="row justify-content-center">
            <div class="col-md-8">
                <i class="fas fa-user"></i>Create a User
                <hr>
                @if($errors->any())
                    <div class="alert alert-danger">
                        <ul>
                            @foreach($errors->all() as $error)
                                <li>{{$error}}</li>
                            @endforeach
                        </ul>
                    </div>
                @endif
                <form action="notes" method="post">
                    @csrf
                    <div class="form-group">
                        <label for="name">Name</label>
                        <input type="text" name="name" class="form-control" placeholder="Name...">
                    </div>
                    <div class="form-group">
                        <label for="email">Email</label>
                        <input type="email" name="email" class="form-control" placeholder="Email...">
                    </div>
                    <div class="form-group">
                        <label for="password">Password</label>
                        <input type="password" name="password" class="form-control" placeholder="Password...">
                    </div>
                    <div class="form-group">
                        <label for="Role">Role</label>
                        <select name="role" class="form-control">
                            <option value="admin">Admin</option>
                            <option value="manager">Manager</option>
                        </select>
                    </div>

                    <button type="submit" class="btn btn-primary">Save</button>
                </form>
            </div>
        </div>
    </div>
@endsection

resources/views/pages/dashboard.blade.php
@extends('layouts.dash', [
    'class' => '',
    'elementActive' => 'dashboard'
])

@section('content')
    <div class="content">
        <div class="row">
            @if(\Illuminate\Support\Facades\Auth::user()->checkAdmin())
                <div class="col-lg-3 col-md-6 col-sm-6">
                    <div class="card card-stats">
                        <div class="card-body ">
                            <div class="row">
                                <div class="col-5 col-md-4">
                                    <div class="icon-big text-center icon-warning">
                                        <i class="nc-icon nc-shop text-warning"></i>
                                    </div>
                                </div>
                                <div class="col-7 col-md-8">
                                    <div class="numbers">
                                        <p class="card-category">Restaurants</p>
                                        <p class="card-title">200
                                        <p>
                                    </div>
                                </div>
                            </div>
                        </div>
                        <div class="card-footer ">
                            <hr>
                            <div class="stats">
                                <i class="fa fa-refresh"></i> View More
                            </div>
                        </div>
                    </div>
                </div>
            @endif
            @if(\Illuminate\Support\Facades\Auth::user()->checkAdmin())
                <div class="col-lg-3 col-md-6 col-sm-6">
                    <div class="card card-stats">
                        <div class="card-body ">
                            <div class="row">
                                <div class="col-5 col-md-4">
                                    <div class="icon-big text-center icon-warning">
                                        <i class="nc-icon nc-user-run text-success"></i>
                                    </div>
                                </div>
                                <div class="col-7 col-md-8">
                                    <div class="numbers">
                                        <p class="card-category">Users</p>
                                        <p class="card-title">10 000
                                        <p>
                                    </div>
                                </div>
                            </div>
                        </div>
                        <div class="card-footer ">
                            <hr>
                            <div class="stats">
                                <i class="fa fa-calendar-o"></i> View More
                            </div>
                        </div>
                    </div>
                </div>
            @endif
            <div class="col-lg-3 col-md-6 col-sm-6">
                <div class="card card-stats">
                    <div class="card-body ">
                        <div class="row">
                            <div class="col-5 col-md-4">
                                <div class="icon-big text-center icon-warning">
                                    <i class="nc-icon nc-shop text-danger"></i>
                                </div>
                            </div>
                            <div class="col-7 col-md-8">
                                <div class="numbers">
                                    <p class="card-category">Orders</p>
                                    <p class="card-title">230
                                    <p>
                                </div>
                            </div>
                        </div>
                    </div>
                    <div class="card-footer ">
                        <hr>
                        <div class="stats">
                            <i class="fa fa-clock-o"></i> View more
                        </div>
                    </div>
                </div>
            </div>
            <div class="col-lg-3 col-md-6 col-sm-6">
                <div class="card card-stats">
                    <div class="card-body ">
                        <div class="row">
                            <div class="col-5 col-md-4">
                                <div class="icon-big text-center icon-warning">
                                    <i class="nc-icon nc-basket text-primary"></i>
                                </div>
                            </div>
                            <div class="col-7 col-md-8">
                                <div class="numbers">
                                    <p class="card-category">Orders pending</p>
                                    <p class="card-title">100
                                    <p>
                                </div>
                            </div>
                        </div>
                    </div>
                    <div class="card-footer ">
                        <hr>
                        <div class="stats">
                            <i class="fa fa-refresh"></i> View more
                        </div>
                    </div>
                </div>
            </div>
        </div>

        <div class="content">
            <div class="row">
                <div class="col-lg-3 col-md-6 col-sm-6">
                    <div class="card card-stats">
                        <div class="card-body ">
                            <div class="row">
                                <div class="col-5 col-md-4">
                                    <div class="icon-big text-center icon-warning">
                                        <i class="nc-icon nc-cart-simple"></i>
                                    </div>
                                </div>
                                <div class="col-7 col-md-8">
                                    <div class="numbers">
                                        <p class="card-category">Orders Completed</p>
                                        <p class="card-title">200
                                        <p>
                                    </div>
                                </div>
                            </div>
                        </div>
                        <div class="card-footer ">
                            <hr>
                            <div class="stats">
                                <i class="fa fa-refresh"></i> View More
                            </div>
                        </div>
                    </div>
                </div>

                @if(\Illuminate\Support\Facades\Auth::user()->checkAdmin())
                    <div class="col-lg-3 col-md-6 col-sm-6">
                        <div class="card card-stats">
                            <div class="card-body ">
                                <div class="row">
                                    <div class="col-5 col-md-4">
                                        <div class="icon-big text-center icon-warning">
                                            <i class="nc-icon nc-money-coins text-success"></i>
                                        </div>
                                    </div>
                                    <div class="col-7 col-md-8">
                                        <div class="numbers">
                                            <p class="card-category">Total Revenue</p>
                                            <p class="card-title">10 000
                                            <p>
                                        </div>
                                    </div>
                                </div>
                            </div>
                            <div class="card-footer ">
                                <hr>
                                <div class="stats">
                                    <i class="fa fa-calendar-o"></i> View More
                                </div>
                            </div>
                        </div>
                    </div>
                @endif
                @if(\Illuminate\Support\Facades\Auth::user()->checkAdmin())
                    <div class="col-lg-3 col-md-6 col-sm-6">
                        <div class="card card-stats">
                            <div class="card-body ">
                                <div class="row">
                                    <div class="col-5 col-md-4">
                                        <div class="icon-big text-center icon-warning">
                                            <i class="nc-icon nc-settings"></i>
                                        </div>
                                    </div>
                                    <div class="col-7 col-md-8">
                                        <div class="numbers">
                                            <p class="card-category">New Customers</p>
                                            <p class="card-title">230
                                            <p>
                                        </div>
                                    </div>
                                </div>
                            </div>
                            <div class="card-footer ">
                                <hr>
                                <div class="stats">
                                    <i class="fa fa-clock-o"></i> View more
                                </div>
                            </div>
                        </div>
                    </div>
                @endif
                <div class="col-lg-3 col-md-6 col-sm-6">
                    <div class="card card-stats">
                        <div class="card-body ">
                            <div class="row">
                                <div class="col-5 col-md-4">
                                    <div class="icon-big text-center icon-warning">
                                        <i class="nc-icon nc-delivery-fast"></i>
                                    </div>
                                </div>
                                <div class="col-7 col-md-8">
                                    <div class="numbers">
                                        <p class="card-category">Delivery Boys</p>
                                        <p class="card-title">100
                                        <p>
                                    </div>
                                </div>
                            </div>
                        </div>
                        <div class="card-footer ">
                            <hr>
                            <div class="stats">
                                <i class="fa fa-refresh"></i> View more
                            </div>
                        </div>
                    </div>
                </div>
            </div>
            @if(\Illuminate\Support\Facades\Auth::user()->checkAdmin())
                <div class="row">
                    <div class="col-md-12">
                        <div class="card ">
                            <div class="card-header ">
                                <h5 class="card-title">Users Behavior</h5>
                                <p class="card-category">24 Hours performance</p>
                            </div>
                            <div class="card-body ">
                                <canvas id=chartHours width="400" height="100"></canvas>
                            </div>
                            <div class="card-footer ">
                                <hr>
                                <div class="stats">
                                    <i class="fa fa-history"></i> Updated 3 minutes ago
                                </div>
                            </div>
                        </div>
                    </div>
                </div>
            @endif

        </div>
    </div>
@endsection

@push('scripts')
    <script>
        $(document).ready(function () {
            // Javascript method's body can be found in assets/assets-for-demo/js/demo.js
            demo.initChartsPages();
        });
    </script>
@endpush

resources/views/pages/edituser.blade.php
@extends('layouts.app', [
    'class' => '',
    'elementActive' => 'editusers'
])

@section('content')
    <div class="container">
        <div class="row justify-content-center">
            <div class="col-md-8">
                <i class="fas fa-user"></i>Edit a User
                <hr>
                @if($errors->any())
                    <div class="alert alert-danger">
                        <ul>
                            @foreach($errors->all() as $error)
                                <li>{{$error}}</li>
                            @endforeach
                        </ul>
                    </div>
                @endif
                <form >

                    <div class="form-group">
                        <label for="name">Name</label>
                        <input type="text" name="name" value="" class="form-control"
                               placeholder="Name...">
                    </div>
                    <div class="form-group">
                        <label for="email">Email</label>
                        <input type="email" name="email" value="" class="form-control"
                               placeholder="Email...">
                    </div>
                    <div class="form-group">
                        <label for="password">Password</label>
                        <input type="password" name="password" class="form-control" placeholder="Password...">
                    </div>
{{--                    <div class="form-group">--}}
{{--                        <label for="Role">Role</label>--}}
{{--                        <select name="role" class="form-control">--}}
{{--                            <option value="admin" {{$user->role == 'admin' ? 'selected':''}}>Admin</option>--}}
{{--                            <option value="cashier" {{$user->role == 'cashier' ? 'selected':''}}>Cashier</option>--}}
{{--                        </select>--}}
{{--                    </div>--}}

                    <button type="submit" class="btn btn-primary">Save</button>
                </form>
            </div>
        </div>
    </div>
@endsection

resources/views/pages/icons.blade.php
@extends('layouts.admin', [
    'class' => '',
    'elementActive' => 'icons'
])

@section('content')
    @can('shop_create')
        <div style="margin-bottom: 10px;" class="row">
            <div class="col-lg-12">
                <a class="btn btn-success" href="{{ route("admin.shops.create") }}">
                    {{ trans('global.add') }} {{ trans('cruds.shop.title_singular') }}
                </a>
            </div>
        </div>
    @endcan
    <div class="card">
        <div class="card-header">
            {{ trans('cruds.shop.title_singular') }} {{ trans('global.list') }}
        </div>

        <div class="card-body">
            <div class="table-responsive">
                <table class=" table table-bordered table-striped table-hover datatable datatable-Shop">
                    <thead>
                    <tr>
                        <th width="10">

                        </th>
                        <th>
                            {{ trans('cruds.shop.fields.id') }}
                        </th>
                        <th>
                            {{ trans('cruds.shop.fields.name') }}
                        </th>
                        <th>
                            {{ trans('cruds.shop.fields.categories') }}
                        </th>
                        <th>
                            {{ trans('cruds.shop.fields.photos') }}
                        </th>
                        <th>
                            {{ trans('cruds.shop.fields.address') }}
                        </th>
                        <th>
                            {{ trans('cruds.shop.fields.active') }}
                        </th>
                        <th>
                            &nbsp;
                        </th>
                    </tr>
                    </thead>
                    <tbody>
                    @foreach(\App\Models\Shop::all() as $shop)
                        <tr data-entry-id="{{ $shop->id }}">
                            <td>

                            </td>
                            <td>
                                {{ $shop->id ?? '' }}
                            </td>
                            <td>
                                {{ $shop->name ?? '' }}
                            </td>
                            <td>
                                @foreach($shop->categories as $key => $item)
                                    <span class="badge badge-info">{{ $item->name }}</span>
                                @endforeach
                            </td>
                            <td>
                                @foreach($shop->photos as $key => $media)
                                    <a href="{{ $media->getUrl() }}" target="_blank">
                                        <img src="{{ $media->getUrl('thumb') }}" width="50px" height="50px">
                                    </a>
                                @endforeach
                            </td>
                            <td>
                                {{ $shop->address ?? '' }}
                            </td>
                            <td>
                                <span style="display:none">{{ $shop->active ?? '' }}</span>
                                <input type="checkbox" disabled="disabled" {{ $shop->active ? 'checked' : '' }}>
                            </td>
                            <td>
                                @can('shop_show')
                                    <a class="btn btn-xs btn-primary" href="{{ route('admin.shops.show', $shop->id) }}">
                                        {{ trans('global.view') }}
                                    </a>
                                @endcan

                                @can('shop_edit')
                                    <a class="btn btn-xs btn-info" href="{{ route('admin.shops.edit', $shop->id) }}">
                                        {{ trans('global.edit') }}
                                    </a>
                                @endcan

                                @can('shop_delete')
                                    <form action="{{ route('admin.shops.destroy', $shop->id) }}" method="POST" onsubmit="return confirm('{{ trans('global.areYouSure') }}');" style="display: inline-block;">
                                        <input type="hidden" name="_method" value="DELETE">
                                        <input type="hidden" name="_token" value="{{ csrf_token() }}">
                                        <input type="submit" class="btn btn-xs btn-danger" value="{{ trans('global.delete') }}">
                                    </form>
                                @endcan

                            </td>

                        </tr>
                    @endforeach
                    </tbody>
                </table>
            </div>


        </div>
    </div>
@endsection
@section('scripts')
    @parent
    <script>
        $(function () {
            let dtButtons = $.extend(true, [], $.fn.dataTable.defaults.buttons)
                @can('shop_delete')
            let deleteButtonTrans = '{{ trans('global.datatables.delete') }}'
            let deleteButton = {
                text: deleteButtonTrans,
                url: "{{ route('admin.shops.massDestroy') }}",
                className: 'btn-danger',
                action: function (e, dt, node, config) {
                    var ids = $.map(dt.rows({ selected: true }).nodes(), function (entry) {
                        return $(entry).data('entry-id')
                    });

                    if (ids.length === 0) {
                        alert('{{ trans('global.datatables.zero_selected') }}')

                        return
                    }

                    if (confirm('{{ trans('global.areYouSure') }}')) {
                        $.ajax({
                            headers: {'x-csrf-token': _token},
                            method: 'POST',
                            url: config.url,
                            data: { ids: ids, _method: 'DELETE' }})
                            .done(function () { location.reload() })
                    }
                }
            }
            dtButtons.push(deleteButton)
            @endcan

            $.extend(true, $.fn.dataTable.defaults, {
                order: [[ 1, 'desc' ]],
                pageLength: 100,
            });
            $('.datatable-Shop:not(.ajaxTable)').DataTable({ buttons: dtButtons })
            $('a[data-toggle="tab"]').on('shown.bs.tab', function(e){
                $($.fn.dataTable.tables(true)).DataTable()
                    .columns.adjust();
            });
        })

    </script>
@endsection